// The R figure drawn live as inline SVG, so her skirt can catch the wind — the
// web twin of WindyFigure in the apps. Path data comes from figure-data.js
// (generated by tools/make_figure_paths.py); the wind maths is the same as
// FigureWind.kt / FigureWind.swift. At gust 0 she is exactly the logo artwork.
// For the opening animation she can also be posed (intro-motion.js): her hat
// and arm move, and setFrame() draws one moment of it.

(function () {
  const DATA = window.ROBE_FIGURE;
  const SVG_NS = "http://www.w3.org/2000/svg";
  const AMPLITUDE = 22, FREQUENCY = 1.15, WAVE = 0.026, LIFT = 0.18;
  const SKIRT_LEFT = 98, SKIRT_RIGHT = 216;
  const reduceMotion = () => window.matchMedia("(prefers-reduced-motion: reduce)").matches;

  const parsed = DATA.paths.map((p) => ({ ...p, xy: p.points.split(" ").map(Number) }));
  const clamp = (t) => Math.min(Math.max(t, 0), 1);
  const smooth = (t) => t * t * (3 - 2 * t);

  function displace(x, y, gust, seconds) {
    if (gust === 0) return [x, y];
    const s = clamp((y - DATA.waistY) / (DATA.hemY - DATA.waistY));
    const ripple = Math.sin(2 * Math.PI * FREQUENCY * seconds - WAVE * y);
    const flare = 0.75 + 0.5 * clamp((x - SKIRT_LEFT) / (SKIRT_RIGHT - SKIRT_LEFT));
    // Mostly blown to the right (the breeze comes from the left), rippling on top.
    const dx = AMPLITUDE * gust * Math.pow(s, 1.6) * flare * (0.55 + 0.45 * ripple);
    const dy = -AMPLITUDE * LIFT * gust * s * s * (0.5 + 0.5 * ripple);
    return [x + dx, y + dy];
  }

  function pathData(xy, gust, seconds) {
    let d = "";
    for (let i = 0; i < xy.length; i += 2) {
      const [x, y] = displace(xy[i], xy[i + 1], gust, seconds);
      d += (i === 0 ? "M" : "L") + x.toFixed(1) + " " + y.toFixed(1);
    }
    return d + "Z";
  }

  /**
   * A new figure: `{ svg, puff(peak, rise, settle), blow(level, seconds), setWeight(trace, fill) }`.
   * It takes `currentColor`, so CSS decides its colour.
   */
  function create(trace = 4, fill = 0.28) {
    const svg = document.createElementNS(SVG_NS, "svg");
    svg.setAttribute("viewBox", `${DATA.minX} ${DATA.minY} ${DATA.width} ${DATA.height}`);
    svg.setAttribute("aria-hidden", "true");
    svg.classList.add("robe-figure");
    const fillGroup = document.createElementNS(SVG_NS, "g");
    const lineGroup = document.createElementNS(SVG_NS, "g");
    fillGroup.setAttribute("fill", "currentColor");
    lineGroup.setAttribute("fill", "currentColor");
    lineGroup.setAttribute("stroke", "currentColor");
    lineGroup.setAttribute("stroke-linejoin", "round");
    lineGroup.setAttribute("stroke-linecap", "round");
    svg.append(fillGroup, lineGroup);

    const skirt = [], hat = [], arm = [];
    parsed.forEach((p, i) => {
      const el = document.createElementNS(SVG_NS, "path");
      el.setAttribute("d", pathData(p.xy, 0, 0));
      (p.dressFill ? fillGroup : lineGroup).appendChild(el);
      if (p.skirt) skirt.push({ el, xy: p.xy });
      if (DATA.hatPaths.includes(i)) hat.push({ el, xy: p.xy });
      if (DATA.armPaths.includes(i)) arm.push({ el, xy: p.xy });
    });

    function posed(xy, place, pose) {
      let d = "";
      for (let i = 0; i < xy.length; i += 2) {
        const [x, y] = place(xy[i], xy[i + 1], pose);
        d += (i === 0 ? "M" : "L") + x.toFixed(1) + " " + y.toFixed(1);
      }
      return d + "Z";
    }

    function setWeight(t, f) {
      lineGroup.setAttribute("stroke-width", String(t));
      fillGroup.setAttribute("fill-opacity", String(f));
    }
    setWeight(trace, fill);

    let puffStart = null, puffPeak = 0, puffRise = 0.28, puffSettle = 1.1;
    let breezeFrom = 0, breezeTo = 0, breezeStart = -1e9, breezeLength = 0.7;
    let running = false;

    const breeze = (now) => breezeFrom + (breezeTo - breezeFrom) * smooth(clamp((now - breezeStart) / breezeLength));
    function gust(now) {
      let puff = 0;
      if (puffStart !== null) {
        const t = now - puffStart;
        if (t < puffRise) puff = puffPeak * (1 - Math.pow(1 - clamp(t / puffRise), 3));
        else if (t < puffRise + puffSettle) puff = puffPeak * (1 - smooth(clamp((t - puffRise) / puffSettle)));
      }
      return Math.max(puff, breeze(now));
    }

    function frame() {
      const now = performance.now() / 1000;
      const g = gust(now);
      skirt.forEach((s) => s.el.setAttribute("d", pathData(s.xy, g, now)));
      const puffing = puffStart !== null && now - puffStart < puffRise + puffSettle;
      if (g > 0 || puffing || breezeTo > 0) requestAnimationFrame(frame);
      else running = false;
    }
    function run() {
      if (running) return;
      running = true;
      requestAnimationFrame(frame);
    }

    return {
      svg,
      setWeight,
      puff(peak = 1, rise = 0.28, settle = 1.1) {
        if (reduceMotion()) return;
        puffStart = performance.now() / 1000;
        puffPeak = peak; puffRise = rise; puffSettle = settle;
        run();
      },
      /** One moment of the opening animation: her pose (RobeIntro) and the skirt's swish. */
      setFrame(pose, swish = 0) {
        const intro = window.RobeIntro;
        if (!intro) return;
        hat.forEach((p) => p.el.setAttribute("d", posed(p.xy, intro.hatPoint, pose)));
        arm.forEach((p) => p.el.setAttribute("d", posed(p.xy, intro.armPoint, pose)));
        const now = performance.now() / 1000;
        skirt.forEach((s) => s.el.setAttribute("d", pathData(s.xy, swish, now)));
      },
      blow(level, seconds = 0.7) {
        if (reduceMotion()) return;
        const now = performance.now() / 1000;
        breezeFrom = breeze(now); breezeTo = level; breezeStart = now; breezeLength = seconds;
        run();
      },
    };
  }

  window.RobeFigure = { create };
})();
